### ISSUE TITLE
Maps / OpenLayers Plugin

### ISSUE THREAD

**Issue by mflue** [roam-qgis/Roam#130]
Hello Nathan,

I wonder if I misunderstand the handling of maps (google maps or open street maps) in Roam. I'm running Roams on an lenovo miix 2 8'' using the centrafuse localisator which works fine so far.
I added different layers to a project (textdelimited and shapefile) which are displayed perfectly but when I try to add a map I fail:
Opening the project in QGIS, either Dufour and Valmiera, the OpenLayersPlugin is not available, even as I reinstalled it twice.
I assume that I will need to add layers as offline maps due to the fact that I wont have internet in the field?
Could you provide any help/advice how to proceed or what I'm doing wring here?

THX Michael

**Comment by Dr-Dray** [comment]
Hi Michael,
just wondering how exactly you managed to get Google Maps/Satellite etc. to work in QGIS via a direct GDAL WMS hookin? I'm struggling to get the Server URL or XML definition file nutted out for these OpenLayers or TMS type services, since I need to use Google/Bing Aerial as a backdrop for some data capture in the field with my Roam App without having to write a plugin etc for it.

Cheers

**Comment by bzeeb** [comment]
Hi @Dr-Dray 

I have not been able to bring in Aerials with a direct hook, however I do regularly bring in Open Street Map using GDAL TMS driver XML:

<GDAL_WMS>
    <Service name="TMS">
        <ServerUrl>http://tile.openstreetmap.org/${z}/${x}/${y}.png</ServerUrl>
    </Service>
    <DataWindow>
        <UpperLeftX>-20037508.34</UpperLeftX>
        <UpperLeftY>20037508.34</UpperLeftY>
        <LowerRightX>20037508.34</LowerRightX>
        <LowerRightY>-20037508.34</LowerRightY>
        <TileLevel>18</TileLevel>
        <TileCountX>1</TileCountX>
        <TileCountY>1</TileCountY>
        <YOrigin>top</YOrigin>
    </DataWindow>
    <Projection>EPSG:900913</Projection>
    <BlockSizeX>256</BlockSizeX>
    <BlockSizeY>256</BlockSizeY>
    <BandsCount>3</BandsCount>
    <Cache />
</GDAL_WMS>

Place this inside a file.xml then drop it on QGIS project and it should load. Make sure your projection is 3857, also it will look poor unless set your project scales to this list:

591659029
295829515
147914757
73957378
36978689
18489344
9244672
4622336
2311168
1155584
577792
288896
144448
72224
36112
18056
9028
4514
2257

Let us know if you manage to bring in some google/bing WMS sources in a similar fashion, would be very interested, not sure if it is still possible since they changed some of their APIs and such.

**Comment by Dr-Dray** [comment]
Thanks for that info and I have managed to achieve the Connection to OSM via both the (OMS XML file + QGIS Add Raster Layer) and using the (OMS Mapnik TMS URL + QGIS Add WMS layer). The second option being a lot easier I feel giving you the options of what layers to choose from within the service, as shown below. The problem is, I want reasonably up-to-date Aerial Ortho photos as per Google Satellite or Bing Aerial OpenLayer services. Hopefully Michael can come back to us and shed some light on how he achieved this direct hookin. Such a pain not to be able to use the QGIS OpenLayers Plugin, if only someone could write an equivalent cutdown Plugin for the Roam App.

OpenStreetMap mapnik:
Bounding box: (-180.0, -85.0511287798, 180.0, 85.0511287798) (show on OSM)
Projection: EPSG:3857 =(WGS 84 /Pseudo Mercator)
WMS half-link: http://irs.gis-lab.info/?layers=osm&
Tiles URL: http://irs.gis-lab.info/?layers=osm&request=GetTile&z=!&x=!&y=!
