### ISSUE TITLE
Images in Select Info are presenting as text

### ISSUE THREAD

**Issue by terry-longmacch** [roam-qgis/Roam#457]
When a layer has Info1 or Info2 select configured to show an image - the same configuration that worked in version 2.7 and showed the image, only shows a string in version 3.0.

Version 2.7
![Version 2_7](https://user-images.githubusercontent.com/35645950/74112493-36fd6880-4bf1-11ea-8ddf-c33ef47ad043.png)

Version 3.0
![Version 3_0](https://user-images.githubusercontent.com/35645950/74112495-3cf34980-4bf1-11ea-9a57-8adc8d7f42b8.png)

**Comment by kalle84** [comment]
having a similar issue.

**Comment by terry-longmacch** [comment]
Could have added HTML to the query, but have hard-coded a solution for fields ending with ".jpg", ".jpeg" or ".png".

**Comment by HeatherHillers** [comment]
@terry-longmacch 

Hi, is this ticket deployed in Version 3.0.6?  I am having a similar issue migrating a Roam 2.7 project to Roam 3.  Although here instead of a string in the attribute list I see a broken image link  The image is saved as expected in _images and shows in if I open the feature form.  -Thanks!

**Comment by terry-longmacch** [comment]
Hi @HeatherHillers ,

I am not having this issue any more, but I have the image path hard-coded in the Info1/Info2 queries.

For example:
SELECT '..\_images\' || filename AS "Photo"
FROM cemeteryphotos
WHERE plotid = :mapkey

Hopefully that works for you.  Let me know if you are still having issues.

Regards,
Terry

**Comment by HeatherHillers** [comment]
Hi @terry-longmacch,

I will try your workaround today,  thanks!  

I have opened a fresh issue on this, because I was able to reproduce it from a fresh project pulled from the master.  I'm tinkering with it a bit in my free time. I almost have it.

https://github.com/roam-qgis/Roam/issues/476

Thanks,

Heather
